// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlDU0oUoFIU3NIMF20HZ5jYTpBVlWTF0',
    appId: '1:552938282575:web:08d8cd038e9b740f6d943a',
    messagingSenderId: '552938282575',
    projectId: 'kompanyonapp-c60f8',
    authDomain: 'kompanyonapp-c60f8.firebaseapp.com',
    storageBucket: 'kompanyonapp-c60f8.appspot.com',
    measurementId: 'G-4FEN5BFFDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkR0zSkfUN0byBXPVsT8zB68mOoDHohDg',
    appId: '1:552938282575:android:909bf0416e49e14b6d943a',
    messagingSenderId: '552938282575',
    projectId: 'kompanyonapp-c60f8',
    storageBucket: 'kompanyonapp-c60f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXQDz2X3822F0Iu5Li71CcelEZPoRPRY',
    appId: '1:552938282575:ios:cef11eaf71a7f0d26d943a',
    messagingSenderId: '552938282575',
    projectId: 'kompanyonapp-c60f8',
    storageBucket: 'kompanyonapp-c60f8.appspot.com',
    iosBundleId: 'com.example.kompanyonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXQDz2X3822F0Iu5Li71CcelEZPoRPRY',
    appId: '1:552938282575:ios:cef11eaf71a7f0d26d943a',
    messagingSenderId: '552938282575',
    projectId: 'kompanyonapp-c60f8',
    storageBucket: 'kompanyonapp-c60f8.appspot.com',
    iosBundleId: 'com.example.kompanyonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlDU0oUoFIU3NIMF20HZ5jYTpBVlWTF0',
    appId: '1:552938282575:web:6c5472af3a86c03a6d943a',
    messagingSenderId: '552938282575',
    projectId: 'kompanyonapp-c60f8',
    authDomain: 'kompanyonapp-c60f8.firebaseapp.com',
    storageBucket: 'kompanyonapp-c60f8.appspot.com',
    measurementId: 'G-BNPGP1RRTT',
  );
}
